# Generated by Django 5.0.14 on 2026-09-28 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_remove_student_behavior_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipFinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Não enviado'), ('SUBMITTED', 'Enviado, aguardando correção'), ('RETURNED_FOR_CORRECTION', 'Devolvido para correção'), ('APPROVED', 'Aprovado'), ('DEPENDENCY', 'Disciplina encerrada sem conclusão (Regime de Dependência)')], default='NOT_SUBMITTED', max_length=30)),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('discipline_term_ends_at', models.DateField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=300)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship_final_report', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('EDUCACAO_INFANTIL', 'Educação Infantil'), ('ENSINO_FUNDAMENTAL_ANOS_INICIAIS', 'Ensino Fundamental — Anos Iniciais'), ('GESTAO_ESCOLAR', 'Gestão Escolar')], max_length=40)),
                ('status', models.CharField(choices=[('NOT_REQUESTED', 'Não solicitado'), ('IN_ANALYSIS', 'Em análise'), ('FORMALIZED', 'Formalizado'), ('REJECTED', 'Indeferido'), ('COMPLETED', 'Concluído')], default='NOT_REQUESTED', max_length=20)),
                ('host_institution', models.CharField(blank=True, max_length=200)),
                ('protocol_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_requirements', to='students.student')),
            ],
            options={
                'ordering': ['student_id', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='InternshipWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROFESSIONAL_ACTIVITY', 'Dispensa por atividades profissionais'), ('NON_MANDATORY_CONVALIDATION', 'Convalidação de estágio não obrigatório')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Em análise'), ('APPROVED', 'Deferido'), ('REJECTED', 'Indeferido')], default='PENDING', max_length=20)),
                ('protocol_number', models.CharField(blank=True, max_length=30)),
                ('approved_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remaining_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_waivers', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='internshiprequirement',
            constraint=models.UniqueConstraint(fields=('student', 'stage'), name='unique_requirement_per_stage'),
        ),
    ]
