# Generated by Django 5.0.14 on 2026-09-27 19:47

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('REGULATION', 'Regulamento'), ('FAQ', 'FAQ'), ('PROCEDURE', 'Procedimento'), ('INTERNSHIP_RULES', 'Regras de estágio'), ('FINANCIAL_GUIDANCE', 'Orientação financeira')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AIExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='gemini', max_length=30)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('prompt_version', models.CharField(blank=True, max_length=30)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('tool', models.CharField(blank=True, max_length=100)),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_executions', to='support.message')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_executions', to='support.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='gemini', max_length=30)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('prompt_version', models.CharField(blank=True, max_length=30)),
                ('cooperation', models.PositiveSmallIntegerField(default=0)),
                ('clarity', models.PositiveSmallIntegerField(default=0)),
                ('respectfulness', models.PositiveSmallIntegerField(default=0)),
                ('warnings', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('justification', models.TextField(blank=True)),
                ('considered_message_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_score', to='support.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.knowledgedocument')),
            ],
        ),
    ]
