# Generated by Django 5.0.14 on 2026-10-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'ChatGPT (OpenAI)'), ('claude', 'Claude (Anthropic)'), ('gemini', 'Gemini (Google)'), ('ollama', 'Ollama (local)')], max_length=20, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('base_url', models.CharField(blank=True, max_length=300)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('REGULATION', 'Regulamento'), ('FAQ', 'FAQ'), ('PROCEDURE', 'Procedimento'), ('INTERNSHIP_RULES', 'Regras de estágio'), ('FINANCIAL_GUIDANCE', 'Orientação financeira')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_sources/')),
                ('raw_text', models.TextField(blank=True, help_text='Alternativa a enviar um arquivo: cole o texto aqui.')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando processamento'), ('PROCESSED', 'Processado'), ('ERROR', 'Erro no processamento')], default='PENDING', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.knowledgedocument')),
            ],
        ),
    ]
