# Generated by Django 5.0.14 on 2026-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiprovidercredential_knowledgesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidercredential',
            name='use_for_embeddings',
            field=models.BooleanField(default=False, help_text='Usado só para gerar embeddings do RAG (busca na base de conhecimento).'),
        ),
        migrations.AlterField(
            model_name='aiprovidercredential',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Usado para classificar e responder o aluno.'),
        ),
    ]
