# Generated by Django 5.0.14 on 2026-09-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(help_text='Primeiro dia do mês de referência')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Aberto'), ('PAID', 'Pago'), ('OVERDUE', 'Vencido'), ('PROCESSING', 'Pagamento não compensado')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='students.student')),
            ],
            options={
                'ordering': ['-reference_month'],
            },
        ),
    ]
