# Generated by Django 5.0.14 on 2026-09-27 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Aluno'), ('MONITOR', 'Monitor')], max_length=10)),
                ('category', models.CharField(choices=[('PROFANITY', 'Palavrão'), ('INSULT', 'Insulto'), ('THREAT', 'Ameaça'), ('DISCRIMINATION', 'Discriminação'), ('HARASSMENT', 'Assédio')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Leve'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=10)),
                ('original_message', models.TextField()),
                ('sanitized_message', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('validator_version', models.CharField(default='regex-v1', max_length=30)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='support.message')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='support.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
