# Generated by Django 5.0.14 on 2026-09-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='behavior_score',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
