# Generated by Django 5.0.14 on 2026-09-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_behavior_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Aluno'), ('MONITOR', 'Atendente'), ('ADMIN', 'Administrador')], default='STUDENT', max_length=20),
        ),
    ]
