# Generated by Django 5.0.14 on 2026-09-27 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=20, unique=True, verbose_name='RA')),
                ('current_period', models.PositiveSmallIntegerField(default=1)),
                ('academic_status', models.CharField(choices=[('REGULAR', 'Regular'), ('PENDING_ENROLLMENT', 'Matrícula pendente'), ('LOCKED', 'Trancado')], default='REGULAR', max_length=25)),
                ('behavior_score', models.PositiveSmallIntegerField(default=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SUBMITTED', 'Entregue'), ('LATE', 'Atrasada'), ('GRADED', 'Corrigida')], default='PENDING', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academic.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ENROLLED', 'Matriculado'), ('IN_PROGRESS', 'Em andamento'), ('PASSED', 'Aprovado'), ('FAILED', 'Reprovado')], default='ENROLLED', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'subject', 'period')},
            },
        ),
    ]
