# Generated by Django 5.0.14 on 2026-09-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='behavior_score',
        ),
    ]
