# Generated by Django 5.0.14 on 2026-09-27 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_remove_student_behavior_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('AI_PROCESSING', 'IA processando'), ('AI_WAITING_USER', 'Aguardando aluno'), ('WAITING_HUMAN', 'Aguardando monitor'), ('HUMAN_ASSIGNED', 'Monitor designado'), ('HUMAN_PROCESSING', 'Em atendimento humano'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Encerrado')], default='OPEN', max_length=20)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('handoff_context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.CharField(blank=True, choices=[('AI', 'IA'), ('HUMAN', 'Humano')], max_length=10, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('STUDENT', 'Aluno'), ('MONITOR', 'Monitor'), ('AI', 'IA'), ('SYSTEM', 'Sistema')], max_length=10)),
                ('original_content', models.TextField()),
                ('displayed_content', models.TextField()),
                ('moderation_status', models.CharField(choices=[('CLEAN', 'Sem restrição'), ('MASKED', 'Mascarada'), ('BLOCKED', 'Bloqueada')], default='CLEAN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
